parameters: {}
environment:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  PINECONE_API_KEY: ${PINECONE_API_KEY}
  PINECONE_ENV: ${PINECONE_ENV}
packages:
  - name: openai-pinecone
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: qa
        binary: false
        main: ""
        runtime: python:3.11
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
